version: 2

sources:
  - name: src_powered_up_pipelines
    quoting: 
      database: true
      schema: true
      identifier: true
    #database: "{{ env_var('target_database') }}"
    #schema: "{{ env_var('target_schema') }}"
    database: "DEV_DB"
    schema: "KAREY"
    tables:
      - name: SRC_CHARLIES_SHOE_EMPORIUM_SALES
        quoting:
          database: true
          schema: true
          identifier: true
        columns:
          - name: TRANSACTION_ID
            tests:
              - unique:
                  config:
                    store_failures: true
              - not_null:
                  config:
                    store_failures: true                
          - name: SALE_INDICATOR
            tests: 
              - dbt_expectations.expect_column_to_exist:
                  config:
                    store_failures: true                    
              - accepted_values:
                  values: ['true','false']
                  #values: ['false']
                  config:
                    store_failures: true                  
        loaded_at_field: LAST_UPDATED
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 5
            period: day
